import { Bitter } from "next/font/google";
import "./globals.css";

const bitter = Bitter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          as="video"
          href="/compressed_demo.mp4"
          type="video/mp4"
        />
      </head>
      <body className={`${bitter.className} antialiased`}>{children}</body>
    </html>
  );
}
